### ISSUE TITLE
数据读取与增强的实现

### ISSUE THREAD

**Issue by qhykwsw** [xinghaochen/Pose-REN#1]
你好，感谢你对手势估计的研究和领域信息的汇总。我想自己重新训练Pose-REN，但是在你提供的caffe-pose中没有发现可以读取手势数据集并引入数据增强的层的实现，请问下能否提供一下呢？还是说是通过别的方法，比如预先处理到本地再来读取的方式来实现。

**Comment by xinghaochen** [comment]
[About data reading and augmentation]
Hi, I will answer this question in English, in case someone else may also be interested :)
We use a new caffe data layer to handle data reading and online augmentation and _currently_ there is no speicfic paln to release this implementation.
There are two ways to handle the data: 
(1) implement a data layer to read the data and perform online data augmentation, which may not cost you much time
(2) preprocess the data and save them into hdf5/lmdb files (which are supported by the official caffe). However, in this manner you may have to use  offline data augmentation, which also works fine but may increase the training time.
Hope that helps.

**Comment by qhykwsw** [comment]
Ok, I see, thanks for your advices.
