### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by zhoushiwei** [xinghaochen/Pose-REN#12]
hi, if I used c++, should I replace all the Python Layer as this :
layer {
  name: "rois_6"
  type: "Python"
  bottom: "prev_pose"
  top: "rois_6"
  python_param {
    module: "python_layers.py_generate_roi_layer"
    layer: "PyGenerateROILayer"
    param_str: "{\'img_w\': 96, \'roi_h\': 6, \'spatial_mul\': 8, \'roi_w\': 6, \'joint_idx\': 6, \'img_h\': 96}"
  }
}

To 

layer {
  name: "rois_15"
  type: "GenerateROI"
  bottom: "prev_pose"
  top: "rois_15"
  generate_roi_param {
    img_w: 96
    roi_h: 6
    spatial_mul: 8
    roi_w: 6
   joint_idx: 17
   img_h: 96
  }
}

**Comment by xinghaochen** [comment]
Python layers should work well in C++ demo. However, sometimes you have to deal with some strange compiling errors so I suggest you using C++ layers.
