### ISSUE TITLE
the result of kinect realtime test is very terrible!

### ISSUE THREAD

**Issue by huangshaoguang** [xinghaochen/Pose-REN#14]
Hello!Thank you very much for sharing! I run your project with kinect2 online and the result is terrible! I don't know why. I've change the fx, fy, ux, uy,lower_,upper_ and dataset parameters as possible to fit my device. Can you help me to check the code? Thank you in advance!
[realtime_kinect.txt](https://github.com/xinghaochen/Pose-REN/files/3385869/realtime_kinect.txt)

**Comment by xinghaochen** [comment]
Pls post some results here so that I can figure out the problems.

**Comment by huangshaoguang** [comment]
Like this. The hand pose can't always fit to the real image, It's a complete mess.
![result](https://user-images.githubusercontent.com/18713992/61119121-bba5ce00-a4cc-11e9-948d-d032260584a9.jpg)

**Comment by xinghaochen** [comment]
Please make sure that the hand is properly segmented (blue box) and check if the depth map is correctly acquired as it looks strange in this image.

**Comment by huangshaoguang** [comment]
OK,thank you very much! Can you tell me the data structure of depth map? Such as the range,data type and shape. Mine is 0-4500, float32, 640*480(the origin is 512*424, I change it by seting the cols 513:640 and the rows 425:480 to zeros)
