### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by fanglinpu** [xinghaochen/Pose-REN#3]
I find it's hard for me to train your proposed model to get the same good result as you have achieved. Therefore, can you release the training code for us to better understand the whole training process or just provide the code for data preprocessing.

**Comment by xinghaochen** [comment]
Hi, you can find details for data preprocessing in the testing code, as we use exactly the same data preprocessing procedure in training and testing. 
More specifically,
(1) Calculate the centers for all images, as in [this file](https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/get_centers.py).
(2) Get the cropped and normalized images, as in [this function](https://github.com/xinghaochen/Pose-REN/blob/master/src/utils/model_pose_ren.py#L105-#L130). Accordingly, you should apply the same transformation on the hand poses.
I'm sorry that currently there is no specific plan to release the training code. Feel free to post in the issues if you have any questions.

**Comment by popper0912** [comment]
> Hi, you can find details for data preprocessing in the testing code, as we use exactly the same data preprocessing procedure in training and testing.
> More specifically,
> (1) Calculate the centers for all images, as in [this file](https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/get_centers.py).
> (2) Get the cropped and normalized images, as in [this function](https://github.com/xinghaochen/Pose-REN/blob/master/src/utils/model_pose_ren.py#L105-#L130). Accordingly, you should apply the same transformation on the hand poses.
> I'm sorry that currently there is no specific plan to release the training code. Feel free to post in the issues if you have any questions.

whether u can send this code to my email? thank u so muck, I'm a green in caffe.
