### ISSUE TITLE
FPS and system specification

### ISSUE THREAD

**Issue by abhigoku10** [xinghaochen/Pose-REN#6]
@xinghaochen  Hi thanks for this wonderful repo , i had following queries 

1. At what fps does it run 
2.does it run on CPU /GPU

**Comment by xinghaochen** [comment]
Hi, we got about 52 fps in a PC equipped with Nvidia 1080 TI GPU and 2.4 GHz E5-2640V4 CPU. However, the codes are not fully optimized and higher speed may be achieved by implementing GPU forward function for GenerateROILayer.  The codes work well in CPU or GPU.
