### ISSUE TITLE
src/testing/predict.py

### ISSUE THREAD

**Issue by liuxunfu** [xinghaochen/Pose-REN#8]
Hi, thanks for this wonderful repo . I had following queries：
       What is "import config" in src/testing/predict.py?Is there a config file missing?

**Comment by xinghaochen** [comment]
Hi, an example of config.py is located in [src/config.py.example](https://github.com/xinghaochen/Pose-REN/blob/master/src/config.py.example), you should run the command:
`cp config.py.example config.py`
and change the settings accordingly, as memtioned in [README](https://github.com/xinghaochen/Pose-REN/blob/master/README.md#inference--evaluation).

**Comment by liuxunfu** [comment]
Ok , thank you very much. I've solved this problem, but there was an error running predict.py, as follows:（I use the 'msra' model）
  Traceback (most recent call last):
  File "predict.py", line 63, in <module>
    main()
  File "predict.py", line 57, in main
    util.save_results(results, out_file)
  File "/home/liu/Desktop/Pose-REN/src/utils/util.py", line 268, in save_results
    f.write('{:.3f} '.format(result[j, k]))
ValueError: Unknown format code 'f' for object of type 'str'

I don't quite understand. I hope the author can help solve this problem. Thank you.

**Comment by xinghaochen** [comment]
Hi, it seems your path to save predicted labels is somehow incorrect.
`python src/testing/predict.py icvl your/path/to/output/file.txt`
Please run the predict.py using the above command. Make sure that the path `your/path/to/output/file.txt` should be existed and have proper write permission.

**Comment by liuxunfu** [comment]
Ok,thank you very much.

**Comment by xinghaochen** [comment]
fixed by the [lastest commit](https://github.com/xinghaochen/Pose-REN/commit/e7f42e1bb05523d2b99d83c2e2eabe45b5f0b894).
